name: Release
on:
  release:
    types: [published]
  # Enable manual run
  workflow_dispatch:
  pull_request: # todo: remove
    branches:
      - master

jobs:
  rebase:
    uses: biolab/orange-ci-cd/.github/workflows/release.yml@wheel-build
    with:
      pure-python: true